excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://MoiAraGui.github.io
name: Guión IV 2015B
description: Misceláneo de reflexiones.
author: Moisés
avatar: http://giffactory.joeyteel.com/mug/sarahjb/Tsumemonmug.gif
ga_domain: 
ga_tracking_id: 